package com.rontseng.model;
// Generated May 27, 2016 4:25:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageLog generated by hbm2java
 */
@Entity
@Table(name = "MessageLog", catalog = "example")
public class MessageLog implements java.io.Serializable {

	private static final long serialVersionUID = -3228264687695569186L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MessageLogId", unique = true, nullable = false)
	private Integer messageLogId;

	@Column(name = "RequestContent", nullable = false)
	private String requestContent;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestTime", nullable = false, length = 19)
	private Date requestTime;

	@Column(name = "ResponseContent", nullable = false)
	private String responseContent;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ResponseTime", length = 19)
	private Date responseTime;

	@Column(name = "URL", nullable = false)
	private String url;

	@Column(name = "HttpMethod", nullable = false)
	private String httpMethod;

	public MessageLog() {
	}

	public MessageLog(String requestContent, Date requestTime) {
		this.requestContent = requestContent;
		this.requestTime = requestTime;
	}

	public MessageLog(String requestContent, Date requestTime, String responseContent, Date responseTime) {
		this.requestContent = requestContent;
		this.requestTime = requestTime;
		this.responseContent = responseContent;
		this.responseTime = responseTime;
	}

	public Integer getMessageLogId() {
		return this.messageLogId;
	}

	public void setMessageLogId(Integer messageLogId) {
		this.messageLogId = messageLogId;
	}

	public String getRequestContent() {
		return this.requestContent;
	}

	public void setRequestContent(String requestContent) {
		this.requestContent = requestContent;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public String getResponseContent() {
		return this.responseContent;
	}

	public void setResponseContent(String responseContent) {
		this.responseContent = responseContent;
	}

	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the httpMethod
	 */
	public String getHttpMethod() {
		return httpMethod;
	}

	/**
	 * @param httpMethod the httpMethod to set
	 */
	public void setHttpMethod(String httpMethod) {
		this.httpMethod = httpMethod;
	}

}
